// AUTO-GENERATED by scripts/convert-html.mjs — script group (body data-scripts) → the inline scripts of that page.
import runAbout1 from './pages/about-1';
import runGetInTouch1 from './pages/get-in-touch-1';
import runHome1 from './pages/home-1';
import runServiceWebDesign1 from './pages/service-web-design-1';
import runWorkTonezone1 from './pages/work-tonezone-1';
import runWorkTonezone2 from './pages/work-tonezone-2';
import runWorkAccounting1 from './pages/work-accounting-1';
// Hand-added (not from a design page): the case study device banner.
import runDeviceSync from './pages/device-sync';

export const pageScripts = {
  "about": [runAbout1],
  "get-in-touch": [runGetInTouch1],
  "home": [runHome1],
  "service-web-design": [runServiceWebDesign1],
  "work-tonezone": [runWorkTonezone1, runWorkTonezone2],
  "work-metrotruck": [runDeviceSync],
  "work-accounting": [runWorkAccounting1, runDeviceSync],
};
