// AUTO-GENERATED by scripts/convert-html.mjs — template name → component.
import ServiceWebDesignTemplate, { META as ServiceWebDesignMeta } from './service-web-design';
import ProductLmsTemplate, { META as ProductLmsMeta } from './product-lms';
import WorkTonezoneTemplate, { META as WorkTonezoneMeta } from './work-tonezone';
import WorkMetrotruckTemplate, { META as WorkMetrotruckMeta } from './work-metrotruck';
import WorkAccountingTemplate, { META as WorkAccountingMeta } from './work-accounting';

export const templates = {
  "service-web-design": { Component: ServiceWebDesignTemplate, meta: ServiceWebDesignMeta },
  "product-lms": { Component: ProductLmsTemplate, meta: ProductLmsMeta },
  "work-tonezone": { Component: WorkTonezoneTemplate, meta: WorkTonezoneMeta },
  "work-metrotruck": { Component: WorkMetrotruckTemplate, meta: WorkMetrotruckMeta },
  "work-accounting": { Component: WorkAccountingTemplate, meta: WorkAccountingMeta },
};
