/* Starter content for the service pages the design did not include. The
   design ships one service page (Website Design); every other service gets
   the same page layout with its own words here. Editors refine it in the
   admin (Services → a service → Its page). Keys are the service template's
   field keys; anything not listed keeps the template's (company-wide) text.

   Each entry: crumb, title [line1, line2], lead, facts [[text, bold]×3],
   challenges [], solutions [], solutionsIntro, benefitsTitle [l1, l2],
   benefits [[title, text]×6], processTitle [l1, l2], steps [[title, text]],
   tech [], faq [[q, a]], workTitle, cta. */
export const SERVICE_PAGES = {
  'e-commerce-development': {
    crumb: 'E-commerce',
    title: ['E-commerce Development Services', 'for Brands That Want to Sell More'],
    lead: 'We build online stores that load fast, convert well and stay easy to run — on Shopify, WooCommerce or a custom platform, with secure payments and the integrations your business depends on.',
    facts: [['Shopify, WooCommerce or', 'custom'], ['Most stores live in', '4–10 weeks'], ['Payments for', 'every market']],
    challengesIntro: 'Growing online stores often struggle with:',
    challenges: ['Slow product and checkout pages', 'High cart abandonment', 'Clunky stock and order management', 'Poor mobile shopping experience', 'Limited payment and shipping options', 'Low visibility in search results', 'Platforms that can’t keep up with growth'],
    solutionsIntro: 'We build stores that solve these problems through:',
    solutions: ['Fast, conversion-focused storefronts', 'A short, secure, mobile-first checkout', 'Inventory, order and ERP integrations', 'Local and international payment gateways', 'Shipping, tax and multi-currency set up properly', 'SEO-ready product and category pages', 'Architecture that scales with your catalogue'],
    benefitsTitle: ['Benefits of our', 'e-commerce development'],
    benefits: [['More Sales From the Same Traffic', 'Clear product pages and a faster checkout turn more visitors into customers.'], ['Easier Store Management', 'Products, orders, stock and discounts managed from one simple dashboard.'], ['Built for Mobile Shoppers', 'Most orders now start on a phone; your store is designed for that first.'], ['Found in Search', 'Clean structure, rich product data and fast pages help you rank.'], ['Secure Payments', 'PCI-compliant gateways, fraud checks and SSL as standard.'], ['Ready to Grow', 'New markets, channels and thousands of products without a rebuild.']],
    processTitle: ['Our e-commerce', 'development process'],
    steps: [['Discovery & Store Planning', 'We map your catalogue, customers, payments, shipping and the systems the store must connect to.'], ['Platform & Architecture', 'We choose Shopify, WooCommerce or a custom build for your size, budget and roadmap.'], ['UX & Store Design', 'Product, category and checkout journeys designed and prototyped before development.'], ['Development & Integrations', 'We build the store and connect payments, shipping, inventory and marketing tools.'], ['Products & Content', 'Catalogue import, product data, SEO metadata and policy pages set up correctly.'], ['Testing & Launch', 'Orders, payments, emails and devices tested end to end before going live.'], ['Growth & Support', 'Ongoing optimisation, updates and support as your store grows.']],
    tech: ['Shopify & Shopify Plus', 'WooCommerce', 'Next.js Commerce', 'Stripe & Razorpay', 'PayPal', 'Headless CMS', 'REST & GraphQL APIs', 'MySQL & PostgreSQL', 'Google Analytics 4', 'Meta Pixel', 'Cloudflare'],
    faq: [['Which platform should my store use?', 'Shopify suits most brands that want speed and simplicity; WooCommerce suits teams already on WordPress; a custom build suits complex pricing, B2B or unusual workflows. We recommend one after discovery.'], ['How long does an online store take?', 'Most stores launch in 4 to 10 weeks, depending on catalogue size, integrations and custom features.'], ['Can you move my existing store to a new platform?', 'Yes. We migrate products, customers and orders and set up redirects so you keep your search rankings.'], ['Which payment gateways can you connect?', 'Stripe, Razorpay, PayPal, PayU and most local gateways, plus cash on delivery and buy-now-pay-later where available.'], ['Will I be able to manage the store myself?', 'Yes. We hand over a store your team can run day to day, with training and documentation.']],
    workTitle: 'E-commerce <span class="grad">in action</span>',
    cta: 'Ready to sell more online?',
  },

  'website-development': {
    crumb: 'Website Development',
    title: ['Website Development Services', 'Built to Perform and Scale'],
    lead: 'Fast, secure, SEO-ready websites for businesses, schools and non-profits — engineered with modern frameworks and easy for your team to update after launch.',
    facts: [['Fast, secure and', 'SEO-ready'], ['Most sites live in', '3–8 weeks'], ['Clients', 'worldwide']],
    challengesIntro: 'Many organisations struggle with:',
    challenges: ['Slow, outdated websites', 'Sites that are hard to update', 'Security issues and broken plugins', 'Poor results in search engines', 'Websites that don’t work well on phones', 'No connection to CRM or marketing tools', 'Expensive rebuilds every few years'],
    solutionsIntro: 'We build websites that solve these problems through:',
    solutions: ['Modern, fast-loading front ends', 'An easy content management system', 'Secure hosting, updates and backups', 'Technical SEO built in from day one', 'Responsive layouts for every screen', 'Integrations with your CRM and tools', 'Clean, maintainable, scalable code'],
    benefitsTitle: ['Benefits of our', 'website development'],
    benefits: [['Speed That Converts', 'Fast pages keep visitors on the site and improve conversions and rankings.'], ['Easy to Update', 'Your team edits pages, news and images without calling a developer.'], ['Secure by Default', 'Hardened hosting, SSL, updates and backups protect your site and data.'], ['Search-Engine Ready', 'Clean code, structured data and good Core Web Vitals help you rank.'], ['Works on Every Device', 'Every page is tested on phones, tablets and desktops.'], ['Room to Grow', 'New sections, languages and integrations added without starting again.']],
    processTitle: ['Our website', 'development process'],
    steps: [['Discovery & Requirements', 'We learn your goals, audience, content and the features the site needs.'], ['Information Architecture', 'Sitemap, page structure and user journeys planned before design starts.'], ['Design & Prototype', 'Visual design and clickable prototypes you approve before development.'], ['Development', 'We build the front end, CMS and integrations with clean, documented code.'], ['Content & SEO', 'Content loaded, metadata written and technical SEO checked.'], ['Testing & Launch', 'Cross-browser, device, speed and accessibility testing, then go-live.'], ['Support & Growth', 'Updates, monitoring and improvements after launch.']],
    tech: ['HTML5 & CSS3', 'JavaScript & TypeScript', 'React & Next.js', 'Vue.js', 'Laravel & PHP', 'Node.js', 'WordPress', 'Headless CMS', 'Tailwind CSS', 'MySQL & PostgreSQL', 'AWS & Vercel', 'Cloudflare'],
    faq: [['How long does it take to build a website?', 'Most business websites take 3 to 8 weeks, depending on the number of pages, features and integrations.'], ['Will I be able to update the website myself?', 'Yes. Every site comes with an easy CMS and a short training session for your team.'], ['Do you provide hosting and maintenance?', 'Yes. We can host, monitor, update and back up your site, or hand it over to your own team.'], ['Is the website SEO-friendly?', 'Yes. Technical SEO, fast loading and clean structure are part of every build.'], ['Can you redesign or rebuild my existing website?', 'Yes. We can modernise your current site and keep your content and search rankings.']],
    workTitle: 'Website development <span class="grad">in action</span>',
    cta: 'Planning a new website?',
  },

  'app-development': {
    crumb: 'App Development',
    title: ['Mobile App Development Services', 'for iOS and Android'],
    lead: 'Native and cross-platform apps for iOS and Android — from the first prototype through store launch and beyond, built to be fast, secure and simple to use.',
    facts: [['Flutter, React Native or', 'native'], ['First release in', '8–16 weeks'], ['Live on', 'both stores']],
    challengesIntro: 'App projects often run into:',
    challenges: ['Unclear scope and growing budgets', 'Separate, costly iOS and Android builds', 'Slow or crash-prone apps', 'Confusing user journeys', 'Hard-to-scale back ends', 'App Store and Play Store rejections', 'No plan for updates after launch'],
    solutionsIntro: 'We deliver apps that avoid these problems through:',
    solutions: ['A clear MVP scope and fixed milestones', 'One cross-platform codebase where it fits', 'Performance and crash monitoring from day one', 'User-tested, intuitive interface design', 'Secure, scalable APIs and cloud back ends', 'Store-ready builds and listing support', 'A maintenance and release roadmap'],
    benefitsTitle: ['Benefits of our', 'app development'],
    benefits: [['Faster Time to Market', 'A focused first version gets your app into users’ hands sooner.'], ['One Team, Both Platforms', 'Design, iOS, Android and the back end delivered by the same team.'], ['Smooth Performance', 'Apps tested on real devices for speed, battery and reliability.'], ['Secure by Design', 'Authentication, encryption and secure APIs protect your users’ data.'], ['Easy to Use', 'Interfaces designed around your users and tested before release.'], ['Built to Evolve', 'Analytics and a clean architecture make every next release easier.']],
    processTitle: ['Our app', 'development process'],
    steps: [['Discovery & MVP Scope', 'We define the problem, the users and the smallest version that proves value.'], ['UX & Prototyping', 'User journeys and a clickable prototype tested before development starts.'], ['Architecture & Back End', 'APIs, database, authentication and cloud services planned and built.'], ['App Development', 'Short cycles with a working build to review at the end of each one.'], ['Testing & QA', 'Functional, performance and security testing across devices and OS versions.'], ['Store Launch', 'Listings, screenshots and privacy details prepared and submitted.'], ['Updates & Growth', 'Crash monitoring, analytics and regular feature releases.']],
    tech: ['Flutter', 'React Native', 'Swift (iOS)', 'Kotlin (Android)', 'Node.js', 'Laravel', 'Firebase', 'REST & GraphQL APIs', 'MySQL & PostgreSQL', 'AWS', 'Google Play Console', 'App Store Connect'],
    faq: [['Native or cross-platform — which is right for us?', 'Cross-platform (Flutter or React Native) suits most business apps and saves time and cost; native suits apps that need heavy device features or maximum performance.'], ['How long does it take to build an app?', 'A focused first version usually takes 8 to 16 weeks, depending on features and integrations.'], ['Do you publish the app to the stores?', 'Yes. We prepare the listings and handle submission to Google Play and the App Store.'], ['Can you build the admin panel and back end too?', 'Yes. We build the APIs, database and web admin panel that power your app.'], ['What happens after launch?', 'We monitor crashes and usage, fix issues and ship improvements on a schedule that suits you.']],
    workTitle: 'App development <span class="grad">in action</span>',
    cta: 'Planning a mobile app?',
  },

  'plugin-development': {
    crumb: 'Plugin Development',
    title: ['Custom Plugin Development', 'for WordPress, Shopify and Web Apps'],
    lead: 'Custom plugins and extensions that add the features your platform is missing — without a rebuild, and without slowing your site down.',
    facts: [['WordPress, Shopify and', 'web apps'], ['Most plugins in', '2–6 weeks'], ['Secure and', 'update-safe']],
    challengesIntro: 'Businesses often struggle with:',
    challenges: ['Off-the-shelf plugins that almost fit', 'Too many plugins slowing the site', 'Manual work the platform can’t automate', 'Systems that don’t talk to each other', 'Plugin conflicts after updates', 'Security holes in abandoned plugins', 'Features locked behind expensive add-ons'],
    solutionsIntro: 'We build plugins that solve these problems through:',
    solutions: ['Features built exactly to your workflow', 'One lightweight plugin instead of many', 'Automation of repetitive tasks', 'Integrations with your CRM, ERP and APIs', 'Code that follows platform standards', 'Security reviews and safe updates', 'Clear documentation and ownership of the code'],
    benefitsTitle: ['Benefits of our', 'plugin development'],
    benefits: [['Exactly What You Need', 'Features designed around your process, not someone else’s.'], ['Faster, Leaner Sites', 'Replace a stack of plugins with one focused, efficient one.'], ['Time Saved', 'Automate the manual steps your team repeats every day.'], ['Connected Systems', 'Sync data between your website and the tools you already use.'], ['Update-Safe', 'Built to platform standards so updates don’t break your site.'], ['You Own the Code', 'Documented source code, yours to keep and extend.']],
    processTitle: ['Our plugin', 'development process'],
    steps: [['Requirements & Audit', 'We map the feature, your workflow and the plugins and systems already in place.'], ['Technical Design', 'Data model, settings, hooks and integrations planned before coding.'], ['Development', 'Clean, documented code that follows the platform’s best practices.'], ['Integration', 'Connections to your APIs, CRM, ERP or payment providers.'], ['Testing', 'Compatibility, performance and security testing on a staging site.'], ['Deployment & Training', 'Installed on your site, with a walkthrough for your team.'], ['Maintenance', 'Updates for new platform versions and ongoing improvements.']],
    tech: ['WordPress & WooCommerce', 'Shopify Apps', 'PHP', 'JavaScript & TypeScript', 'React', 'Node.js', 'Laravel', 'REST & GraphQL APIs', 'Webhooks', 'MySQL', 'Composer & npm', 'Git'],
    faq: [['Can you extend an existing plugin instead of building a new one?', 'Often, yes. We review what you have and extend it where that is safer and cheaper than starting again.'], ['How long does a custom plugin take?', 'Most plugins take 2 to 6 weeks, depending on features and integrations.'], ['Will the plugin slow my site down?', 'No. We build lean, cached and well-tested code, and often replace several heavier plugins.'], ['What happens when WordPress or Shopify updates?', 'Our plugins follow platform standards, and we offer maintenance to keep them compatible.'], ['Do I own the plugin code?', 'Yes. You receive the documented source code.']],
    workTitle: 'Plugin development <span class="grad">in action</span>',
    cta: 'Missing a feature on your platform?',
  },

  'seo-services': {
    crumb: 'SEO',
    title: ['SEO Services That Bring', 'Qualified Traffic and Leads'],
    lead: 'Technical SEO, content and link building that move your pages up search results — with monthly reports you can actually read.',
    facts: [['Technical, content and', 'off-page'], ['First results in', '6–12 weeks'], ['Clear monthly', 'reports']],
    challengesIntro: 'Many businesses struggle with:',
    challenges: ['Low rankings for important keywords', 'Little or no organic traffic', 'Technical errors blocking indexing', 'Thin or outdated content', 'Few quality backlinks', 'Poor local search visibility', 'Reports that don’t show real results'],
    solutionsIntro: 'We improve your search performance through:',
    solutions: ['A full technical SEO audit and fixes', 'Keyword research tied to revenue', 'Content plans and on-page optimisation', 'Ethical, quality link building', 'Local SEO and Google Business Profile', 'Speed and Core Web Vitals improvements', 'Plain-English monthly reporting'],
    benefitsTitle: ['Benefits of our', 'SEO services'],
    benefits: [['Visitors With Intent', 'People who find you through search are already looking for what you offer.'], ['Results That Compound', 'Rankings keep bringing visitors long after the work is done.'], ['Lower Cost per Lead', 'Organic traffic reduces how much you depend on paid ads.'], ['Local Visibility', 'Show up in maps and local searches where your customers are.'], ['Better Website Health', 'Technical fixes improve speed and user experience too.'], ['Clear Reporting', 'Track rankings, traffic and leads with reports you understand.']],
    processTitle: ['Our SEO', 'process'],
    steps: [['SEO Audit', 'We review your site’s technical health, content, links and competitors.'], ['Keyword Strategy', 'Keywords chosen by search volume, intent and business value.'], ['Technical Fixes', 'Indexing, speed, structure and structured-data issues resolved.'], ['On-Page Optimisation', 'Titles, headings, content and internal links improved page by page.'], ['Content & Links', 'New content and quality backlinks build authority over time.'], ['Local SEO', 'Google Business Profile, citations and reviews for local search.'], ['Reporting & Refinement', 'Monthly reports and adjustments based on what is working.']],
    tech: ['Google Search Console', 'Google Analytics 4', 'Ahrefs', 'Semrush', 'Screaming Frog', 'PageSpeed Insights', 'Schema.org', 'Google Business Profile', 'Looker Studio', 'Yoast & Rank Math'],
    faq: [['How long does SEO take to work?', 'Technical fixes can help within weeks; meaningful ranking gains usually take three to six months of consistent work.'], ['Do you guarantee first-page rankings?', 'No one can honestly guarantee rankings. We commit to proven work, clear targets and transparent reporting.'], ['What do your monthly reports include?', 'Rankings, organic traffic, conversions and leads, plus what we did and what comes next.'], ['Do you do local SEO?', 'Yes. We optimise your Google Business Profile, local citations and location pages.'], ['Can you fix SEO on my existing website?', 'Yes. We start with an audit and fix the issues holding your site back.']],
    workTitle: 'SEO <span class="grad">in action</span>',
    cta: 'Want your business to rank higher?',
  },

  'customise-shopify-theme-development': {
    crumb: 'Shopify Themes',
    title: ['Custom Shopify Theme Development', 'That Matches Your Brand'],
    lead: 'Bespoke Shopify themes and customisations that look like your brand, load fast and make it easy for shoppers to buy.',
    facts: [['Online Store', '2.0 themes'], ['Most themes in', '3–6 weeks'], ['Fast and', 'conversion-ready']],
    challengesIntro: 'Shopify merchants often struggle with:',
    challenges: ['Templates that look like everyone else', 'Slow themes overloaded with apps', 'Layouts that are hard to change', 'Poor product page conversion', 'Mobile layouts that feel cramped', 'Brand guidelines the theme can’t follow', 'Customisations that break on updates'],
    solutionsIntro: 'We build themes that solve these problems through:',
    solutions: ['A unique, on-brand storefront design', 'Lightweight code with fewer apps', 'Flexible sections editable in the theme editor', 'Conversion-focused product pages', 'Mobile-first layouts', 'Brand fonts, colours and imagery done properly', 'Update-safe Online Store 2.0 architecture'],
    benefitsTitle: ['Benefits of a', 'custom Shopify theme'],
    benefits: [['A Store That Stands Out', 'A design built for your brand, not a template shared by thousands.'], ['Faster Loading', 'Lean code and fewer apps make pages load quickly.'], ['Easy to Edit', 'Drag-and-drop sections let your team change pages without code.'], ['Higher Conversions', 'Product, collection and cart pages designed to sell.'], ['Mobile-First', 'Built for the phones most of your shoppers use.'], ['Future-Proof', 'Online Store 2.0 themes that keep working as Shopify evolves.']],
    processTitle: ['Our Shopify theme', 'process'],
    steps: [['Brand & Store Review', 'We review your brand, products, competitors and current store data.'], ['UX & Wireframes', 'Home, collection, product and cart layouts planned for conversion.'], ['Visual Design', 'A custom design for desktop and mobile you approve before build.'], ['Theme Development', 'Liquid sections and blocks your team can edit in the theme editor.'], ['Apps & Integrations', 'Only the apps you need, configured and integrated cleanly.'], ['Testing & Launch', 'Speed, devices and checkout tested before the new theme goes live.'], ['Optimisation', 'Ongoing tweaks based on analytics and customer behaviour.']],
    tech: ['Shopify Liquid', 'Online Store 2.0', 'Shopify CLI', 'Dawn', 'JavaScript', 'Tailwind CSS', 'Shopify Apps', 'Shopify Markets', 'Metafields', 'Google Analytics 4', 'Meta Pixel'],
    faq: [['Can you customise my existing Shopify theme?', 'Yes. We can improve your current theme or build a fully custom one, depending on your goals and budget.'], ['How long does a custom theme take?', 'Most custom themes take 3 to 6 weeks from design approval.'], ['Will I be able to edit the theme myself?', 'Yes. We build flexible sections you can edit in Shopify’s theme editor.'], ['Will a custom theme slow my store down?', 'No — custom themes are usually faster, because they include only what your store needs.'], ['Can you migrate my store to Shopify?', 'Yes. We can migrate products, customers and orders from most platforms.']],
    workTitle: 'Shopify themes <span class="grad">in action</span>',
    cta: 'Ready to stand out on Shopify?',
  },

  'plasmic-development': {
    crumb: 'Plasmic Development',
    title: ['Plasmic Development Services', 'for Fast, Visual Websites'],
    lead: 'Websites built visually with Plasmic and engineered with real code — so your marketing team can publish pages without waiting on developers.',
    facts: [['Visual editing with', 'real code'], ['Most sites live in', '3–6 weeks'], ['Your team', 'publishes']],
    challengesIntro: 'Teams often struggle with:',
    challenges: ['Waiting on developers for every page', 'Website builders that look generic', 'Slow, bloated no-code sites', 'Campaign pages that take weeks', 'Inconsistent design across pages', 'Limited integrations with real data', 'Sites that can’t grow beyond the builder'],
    solutionsIntro: 'We build Plasmic sites that solve these problems through:',
    solutions: ['A visual editor your team can use', 'A custom design system and components', 'Fast Next.js front ends', 'Landing pages built in hours, not weeks', 'Reusable, on-brand components', 'Connections to your CMS, APIs and data', 'Code you can extend at any time'],
    benefitsTitle: ['Benefits of', 'Plasmic development'],
    benefits: [['Marketing Moves Faster', 'Launch and change pages without a developer in the loop.'], ['Consistent Design', 'Shared components keep every page on brand.'], ['Real Performance', 'Pages render as fast, optimised Next.js code.'], ['Connected to Your Data', 'Pull content and products from your CMS or APIs.'], ['No Lock-In', 'Developers can extend the site with code whenever needed.'], ['Lower Ongoing Cost', 'Fewer development hours for everyday changes.']],
    processTitle: ['Our Plasmic', 'development process'],
    steps: [['Discovery', 'We learn which pages your team creates and how often they change.'], ['Design System', 'Colours, type and reusable components set up in Plasmic.'], ['Page Templates', 'Templates for the pages your team builds most often.'], ['Code Integration', 'Plasmic connected to a Next.js app, your CMS and APIs.'], ['Performance & SEO', 'Pages optimised for speed, metadata and search.'], ['Training & Handover', 'Your team learns to build and publish pages themselves.'], ['Support', 'New components and improvements as your needs grow.']],
    tech: ['Plasmic', 'Next.js', 'React', 'TypeScript', 'Headless CMS', 'Vercel', 'REST & GraphQL APIs', 'Tailwind CSS', 'Google Analytics 4', 'Cloudflare'],
    faq: [['What is Plasmic?', 'Plasmic is a visual builder for React and Next.js: designers and marketers edit pages visually while developers keep full control of the code.'], ['Can my team really edit the site without developers?', 'Yes. Once components and templates are set up, your team can build and publish pages on their own.'], ['Is a Plasmic site fast?', 'Yes. Pages are rendered as optimised Next.js code, so they load as fast as hand-coded sites.'], ['Can Plasmic connect to our CMS or product data?', 'Yes. We connect it to your CMS, e-commerce platform or APIs.'], ['How long does a Plasmic website take?', 'Most Plasmic websites take 3 to 6 weeks, including the component library.']],
    workTitle: 'Plasmic development <span class="grad">in action</span>',
    cta: 'Want a faster way to build your website?',
  },

  'event-microsites': {
    crumb: 'Event Microsites',
    title: ['Event Microsites and', 'Campaign Websites'],
    lead: 'Focused microsites for events, launches and campaigns — registration, interactive experiences and live updates, delivered on tight deadlines.',
    facts: [['Registration, games and', 'live updates'], ['Launch-ready in', '1–4 weeks'], ['Built for', 'traffic spikes']],
    challengesIntro: 'Event and campaign teams often struggle with:',
    challenges: ['Tight launch deadlines', 'Main websites too rigid for campaigns', 'Registration forms that lose sign-ups', 'Sites that crash under traffic spikes', 'Little engagement beyond a landing page', 'No clear way to measure results', 'Content that needs changing during the event'],
    solutionsIntro: 'We build microsites that solve these problems through:',
    solutions: ['Fast turnaround on proven components', 'Standalone sites designed for the campaign', 'Simple, mobile-first registration flows', 'Scalable hosting that handles spikes', 'Interactive features like scratch-and-win', 'Analytics and conversion tracking built in', 'Easy updates before and during the event'],
    benefitsTitle: ['Benefits of our', 'event microsites'],
    benefits: [['On Time, Every Time', 'Built around your launch date, with buffers for approvals.'], ['More Registrations', 'Short, mobile-friendly forms convert more visitors.'], ['Higher Engagement', 'Games, polls and countdowns keep audiences involved.'], ['Ready for Traffic', 'Cloud hosting and caching handle sudden spikes.'], ['Measurable Results', 'Track sign-ups, plays and conversions in real time.'], ['Reusable for Next Time', 'Components you can reuse for future events.']],
    processTitle: ['Our microsite', 'process'],
    steps: [['Brief & Goals', 'We agree the audience, goals, dates and what success looks like.'], ['Concept & Design', 'A campaign look and key screens designed for mobile first.'], ['Build', 'Pages, registration and interactive features built on proven components.'], ['Integrations', 'CRM, email, payments or ticketing connected where needed.'], ['Load & QA Testing', 'Tested on devices and under expected traffic before launch.'], ['Launch & Live Support', 'We stay on hand during the campaign for updates and fixes.'], ['Reporting', 'A summary of traffic, registrations and engagement afterwards.']],
    tech: ['Next.js', 'React', 'Tailwind CSS', 'GSAP', 'Node.js', 'Firebase', 'Vercel', 'Cloudflare', 'Google Analytics 4', 'Mailchimp', 'HubSpot'],
    faq: [['How quickly can you build a microsite?', 'Simple event sites can launch in about a week; interactive campaigns usually take 2 to 4 weeks.'], ['Can you add registration or ticketing?', 'Yes. We build registration forms and can connect ticketing, payments and your CRM.'], ['Can the site handle a big traffic spike?', 'Yes. We host on scalable cloud infrastructure and load-test before launch.'], ['Do you build interactive games like scratch-and-win?', 'Yes. We build games, quizzes, polls and countdowns tied to your campaign goals.'], ['What happens after the event?', 'We can archive the site, turn it into a recap page, or reuse it for your next event.']],
    workTitle: 'Campaigns <span class="grad">in action</span>',
    cta: 'Planning a campaign microsite?',
  },
};

/* Overrides for one service, as template field values. `base` is the
   template's defaults (icons and other per-item values are reused). */
export function servicePageData(slug, base) {
  const s = SERVICE_PAGES[slug];
  if (!s) return null;
  const facts = (base['top.itemList'] || []).map((it, i) => ({ ...it, itemText: s.facts[i]?.[0] ?? it.itemText, bold: s.facts[i]?.[1] ?? it.bold }));
  const cards = (base['benefits.cardList'] || []);
  return {
    ...base,
    'top.crumb': base['top.crumb'].replace(/<span aria-current="page">[^<]*<\/span>/, `<span aria-current="page">${s.crumb}</span>`),
    'top.titleLine': s.title[0],
    'top.titleLine2': s.title[1],
    'top.lead': s.lead,
    'top.itemList': facts,
    'approach.text': s.challengesIntro,
    'approach.itemList': s.challenges.map((itemText) => ({ itemText })),
    'approach.text2': s.solutionsIntro,
    'approach.itemList2': s.solutions.map((itemText) => ({ itemText })),
    'benefits.titleLine': s.benefitsTitle[0],
    'benefits.titleLine2': s.benefitsTitle[1],
    'benefits.cardList': s.benefits.map(([subheading, text], i) => ({ ...(cards[i % cards.length] || {}), subheading, text })),
    'process.titleLine': s.processTitle[0],
    'process.titleLine2': s.processTitle[1],
    'process.stepList': s.steps.map(([subheadingText, text]) => ({ subheadingText, text })),
    'process.itemList': s.tech.map((item) => ({ item })),
    'faq.questionList': s.faq.map(([q, a]) => ({ text: q, blockLabel: q, text2: a })),
    'case-studies.titleLine': s.workTitle,
    'start.heading': s.cta,
  };
}
